cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"

brew "act"
brew "awscli"
brew "ghq"
brew "git"
brew "go"
brew "kotlin"
brew "nvm"
brew "peco"
brew "protobuf"
brew "rbenv"
brew "readline"
brew "ruby-build"
brew "rust"
brew "terraform"
brew "tree"
brew "vim"
brew "zsh"
brew "zsh-completions"

# Applications

cask "1password"
cask "1password-cli"
cask "android-studio"
cask "appcleaner"
cask "alfred"
cask "dash"
cask "deepl"
cask "docker"
cask "figma"
cask "github"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "hammerspoon"
cask "insomnia"
cask "iterm2-beta"
cask "karabiner-elements"
cask "kindle"
cask "notion"
cask "sequel-pro"
cask "slack-beta"
cask "the-unarchiver"
cask "visual-studio-code"
cask "zoom"

# Fonts

cask "font-jetbrains-mono"
