cask_args appdir: "/Applications"
tap "hashicorp/tap"

brew "act"
brew "awscli"
brew "gh"
brew "ghq"
brew "git"
brew "terraform"
brew "peco"
brew "mise"
brew "ripgrep"
brew "sqlite"
brew "sheldon"
brew "starship"
brew "tree"
brew "vim"
brew "zsh"
brew "zsh-autosuggestions"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

# Applications
cask "claude-code"
cask "codex"
cask "appcleaner"
cask "figma"
cask "gcloud-cli"
cask "ghostty@tip"
cask "github"
cask "hammerspoon"
cask "insomnia"
cask "iterm2"
cask "orbstack"
cask "karabiner-elements"
cask "notion"
cask "visual-studio-code"

# Fonts
cask "font-jetbrains-mono"
