#!/bin/bash
set -euo pipefail

GHQ_ROOT="$HOME/src"
GITHUB_HOST="github.com"
GITHUB_USERNAME="kajiken"
GITHUB_REPOSITORY="palette"

info () {
  printf "\r  \033[00;34m>>>\033[0m %s\n" "$1"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] %s\n" "$1"
}

info "Start installing..."
echo ''

mkdir -p "$GHQ_ROOT/$GITHUB_HOST/$GITHUB_USERNAME"
cd "$GHQ_ROOT/$GITHUB_HOST/$GITHUB_USERNAME"

info "› git clone"
if [ ! -d "$GITHUB_REPOSITORY" ]; then
  git clone "https://github.com/$GITHUB_USERNAME/$GITHUB_REPOSITORY.git"
fi

cd "$GHQ_ROOT/$GITHUB_HOST/$GITHUB_USERNAME/$GITHUB_REPOSITORY"

# Check for Homebrew
if ! command -v brew >/dev/null 2>&1; then
  info "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

info "› brew bundle"
brew bundle

echo ''
success "All installed!"
