export GOPATH=$HOME
export PATH=$GOPATH/bin:$PATH

export LANG=en_US.UTF-8
export HGENCODING=utf-8
export EDITOR=vim
export LSCOLORS=gxfxcxdxbxegedabagacad

export GIT_MERGE_AUTOEDIT=no

# history setting
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000

export REPORTTIME=3
