# ====================
#     .zshrc file
# ====================

if type brew &>/dev/null; then
  HOMEBREW_PREFIX=$(brew --prefix)
  FPATH=$HOMEBREW_PREFIX/share/zsh-completions:$FPATH

  source $HOMEBREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
  source $HOMEBREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh

  export GHQPATH=$HOMEBREW_PREFIX/bin/ghq
fi

export DOTFILES_REPOS='kajiken/palette'
_ghq_root=$($GHQPATH root)
_dotfiles_path=$_ghq_root/$($GHQPATH list $DOTFILES_REPOS)
export ZSH=$_dotfiles_path/zsh
unset _ghq_root _dotfiles_path
export XDG_CONFIG_HOME=$HOME/.config

source $ZSH/aliases.zsh
source $ZSH/keybind.zsh
source $ZSH/options.zsh
source $ZSH/lib/peco.zsh

autoload -Uz compinit
_zcompdump="${XDG_CACHE_HOME:-${HOME}/.cache}/zsh/.zcompdump-${HOST}-${ZSH_VERSION}"
mkdir -p "${_zcompdump:h}"

setopt extendedglob
if [[ -n "${_zcompdump}"(#qN.mh+24) ]]; then
  compinit -d "${_zcompdump}"
else
  compinit -C -d "${_zcompdump}"
fi

eval "$(starship init zsh)"
eval "$(mise activate zsh)"
